name: Create Files, Attest & Verify

on:
  push:
    branches: [ Plain_version ]

jobs:
  create-and-attest:
    name: Create 3 files & generate attestation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write          # needed to create attestation
      attestations: write      # needed to upload attestation

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create 3 files
        run: |
          mkdir output
          echo "File A content" > output/file-a.txt
          echo "File B content" > output/file-b.txt
          echo "File C content" > output/file-c.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: output/

      - name: Create provenance attestation
        id: provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: "output/**"

      - name: Save attestation path
        run: |
          echo "ATTESTATION_PATH=$(cat $RUNNER_TEMP/created_attestation_paths.txt)" >> $GITHUB_ENV


  verify-attestation:
    name: Verify attestation in next job
    needs: create-and-attest
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: output-files
          path: output/

      # gh is already installed on GitHub-hosted runners
      - name: Verify attestation
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh attestation verify output/ \
            -R ${{ github.repository }}
